spring.application.name=locadora

spring.datasource.url=jdbc:h2:mem:locadora
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=myllena
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect